# playbook to help with install
---
- hosts: all
  tasks:
    - name: "Install dependencies"
      become: yes
      apt:
        name: 
          - libsdl1.2-dev
          - libsdl-image1.2-dev
          - libsdl-ttf2.0-dev
          - mosquitto
